version: '3.8'

services:
  meu-postgres:
    image: postgres:16-alpine

    container_name: postgres-local

    environment:
      POSTGRES_USER: devuser               # Usu치rio que ser치 criado
      POSTGRES_PASSWORD: devpass           # Senha para este usu치rio
      POSTGRES_DB: communitex            # Nome do banco de dados que ser치 criado

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local